import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import {
  formatDrillAssignmentDescription,
  type CustomDrillPayload,
  type LibraryDrillRow,
} from '@/lib/drills-library'
import { syncCoachabilityForPlayer } from '@/lib/journey-coachability-sync'
import { triggerCoachabilitySync } from '@/lib/journey-coachability-trigger'

export async function assignLibraryDrillToPlayer(
  supabase: SupabaseClient,
  playerId: string,
  options: { libraryDrillId?: string; customDrillData?: CustomDrillPayload },
): Promise<
  | { success: true; drillId: string; title: string; libraryDrillId: string | null }
  | { success: false; error: string; details?: string }
> {
  let libraryDrillId: string | null = null
  let title: string
  let description: string

  if (options.libraryDrillId) {
    const { data: libDrill, error: libError } = await supabase
      .from('drills_library')
      .select('*')
      .eq('id', options.libraryDrillId)
      .maybeSingle()

    if (libError || !libDrill) {
      return { success: false, error: 'Library drill not found' }
    }

    libraryDrillId = libDrill.id
    title = libDrill.name
    description = formatDrillAssignmentDescription(libDrill as LibraryDrillRow)
  } else if (options.customDrillData) {
    const custom = options.customDrillData
    const slug = `custom-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    const { data: newLibraryDrill, error: createError } = await supabase
      .from('drills_library')
      .insert({
        slug,
        name: custom.name,
        primary_category: custom.primary_category,
        drill_type: custom.drill_type ?? null,
        checkpoints: custom.checkpoints ?? [],
        skill_level: custom.skill_level,
        duration_minutes: custom.duration_minutes,
        mode: custom.mode,
        requires: custom.requires ?? [],
        description: custom.description,
        steps: custom.steps,
        success_criteria: custom.success_criteria ?? null,
        coaching_cue: custom.coaching_cue ?? null,
        source: 'ai_generated',
        source_attribution: 'Generated by Via',
        is_public: false,
        created_by_player_id: playerId,
      })
      .select('id, name, description, duration_minutes, primary_category, coaching_cue, steps')
      .single()

    if (createError || !newLibraryDrill) {
      return {
        success: false,
        error: 'Failed to save custom drill',
        details: createError?.message,
      }
    }

    libraryDrillId = newLibraryDrill.id
    title = newLibraryDrill.name
    description = formatDrillAssignmentDescription(newLibraryDrill as LibraryDrillRow)
  } else {
    return {
      success: false,
      error: 'Must provide library_drill_id or custom_drill_data',
    }
  }

  const { data: existing } = await supabase
    .from('drills')
    .select('id')
    .eq('player_id', playerId)
    .eq('title', title)
    .is('completed_at', null)
    .maybeSingle()

  if (existing) {
    return {
      success: true,
      drillId: existing.id,
      title,
      libraryDrillId,
    }
  }

  const { data: assignedDrill, error: assignError } = await supabase
    .from('drills')
    .insert({
      player_id: playerId,
      title,
      description,
      library_drill_id: libraryDrillId,
    })
    .select('id')
    .single()

  if (assignError || !assignedDrill) {
    return {
      success: false,
      error: 'Failed to assign drill',
      details: assignError?.message,
    }
  }

  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  if (serviceKey && supabaseUrl) {
    const admin = createClient(supabaseUrl, serviceKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    })
    try {
      await syncCoachabilityForPlayer(admin, playerId)
    } catch (e) {
      console.error('[assign-library-drill] sync failed:', e)
      triggerCoachabilitySync(playerId)
    }
  } else {
    triggerCoachabilitySync(playerId)
  }

  return {
    success: true,
    drillId: assignedDrill.id,
    title,
    libraryDrillId,
  }
}
